"use client";

import { BarChart3, Box, CheckCircle2, PackageCheck, Plus, RotateCcw, Save, ShoppingCart, Users, X } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";

export type Order={id:number;number:string;customerId:number;status:string;paymentStatus:string;totalCents:number;channel:string;createdAt:string;customer:string;itemCount:number};
export type Product={id:number;sku:string;name:string;category:string;stock:number;reservedStock:number;reorderPoint:number;priceCents:number;status:string;createdAt:string};
export type Customer={id:number;name:string;email:string;segment:string;totalSpentCents:number;orderCount:number;createdAt:string};
export type Dashboard={summary:{revenueCents:number;orderCount:number;averageTicketCents:number;ordersToday:number};orders:Order[];inventory:Product[];customers:Customer[];channels:Array<{channel:string;orders:number;revenueCents:number}>;trend:Array<{day:string;revenueCents:number}>;topProducts:Array<{name:string;sku:string;units:number;revenueCents:number}>;stockMovements:Array<{id:number;productId:number;type:string;quantity:number;actor:string;createdAt:string;product:string;sku:string;orderNumber:string|null}>};
export type Session={email:string;name:string;role:"admin"|"manager"|"viewer";permissions:string[]};
export type View="overview"|"orders"|"products"|"customers"|"inventory"|"reports"|"settings";
type Report={period:number;summary:{revenueCents:number;orderCount:number;averageTicketCents:number;cancellationRate:number;fulfillmentRate:number;revenueGrowth:number};categories:Array<{category:string;units:number;revenueCents:number}>;channels:Array<{channel:string;orders:number;revenueCents:number}>;inventory:{stockValueCents:number;physicalUnits:number;reservedUnits:number;criticalProducts:number}};

export const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export const date=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
export const statusCopy:Record<string,string>={pending:"Pendente",paid:"Pago",processing:"Preparando",shipped:"Enviado",delivered:"Entregue",canceled:"Cancelado"};
export const channelCopy:Record<string,string>={store:"Loja própria",marketplace:"Marketplace",social:"Social commerce"};
export const roleCopy={admin:"Administrador",manager:"Gestor",viewer:"Leitor"};
const segmentCopy:Record<string,string>={new:"Novo",returning:"Recorrente",vip:"VIP"};
const next:Record<string,string[]>={pending:["paid","canceled"],paid:["processing","canceled"],processing:["shipped","canceled"],shipped:["delivered"],delivered:[],canceled:[]};
export const currency=(cents:number)=>money.format(Number(cents??0)/100);
export const initials=(value:string)=>value.split(" ").slice(0,2).map(part=>part[0]).join("").toUpperCase();
export function EmptyChart(){return <div className="chart-empty">Aguardando histórico de vendas</div>}

function Toast({message,close}:{message:string;close:()=>void}){return message?<div className="commerce-toast"><CheckCircle2 size={15}/>{message}<button onClick={close} aria-label="Fechar"><X size={13}/></button></div>:null}
function Panel({title,subtitle,action,children}:{title:string;subtitle:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="commerce-panel management-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</header>{children}</section>}

export function OrdersWorkspace({data,query,refresh}:{data:Dashboard;query:string;refresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(0),[message,setMessage]=useState("");
 const q=query.toLowerCase(); const rows=data.orders.filter(o=>!q||`${o.number} ${o.customer} ${statusCopy[o.status]}`.toLowerCase().includes(q));
 async function move(order:Order,status:string){setBusy(order.id);const r=await fetch(`/api/orders/${order.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const body=await r.json() as {error?:string};setMessage(r.ok?`Pedido ${order.number} atualizado.`:body.error??"Não foi possível atualizar.");if(r.ok)await refresh();setBusy(0)}
 return <><section className="workspace-kpis"><article><ShoppingCart/><span><small>Total</small><strong>{data.orders.length}</strong></span></article>{["pending","processing","shipped"].map(s=><article key={s}><PackageCheck/><span><small>{statusCopy[s]}</small><strong>{data.orders.filter(o=>o.status===s).length}</strong></span></article>)}</section><Panel title="Fila de pedidos" subtitle="Avance cada pedido com histórico e consistência de estoque"><div className="management-table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Status</th><th>Canal</th><th>Total</th><th>Próxima ação</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><strong>{o.number}</strong><small>{o.itemCount} itens</small></td><td>{o.customer}</td><td><span className={`order-status status-${o.status}`}>{statusCopy[o.status]}</span></td><td>{channelCopy[o.channel]}</td><td><strong>{currency(o.totalCents)}</strong></td><td><select disabled={busy===o.id||!next[o.status]?.length} value="" onChange={e=>move(o,e.target.value)}><option value="">{busy===o.id?"Salvando...":"Selecionar"}</option>{next[o.status]?.map(s=><option key={s} value={s}>{statusCopy[s]}</option>)}</select></td></tr>)}</tbody></table></div></Panel><Toast message={message} close={()=>setMessage("")}/></>
}

export function ProductsWorkspace({data,query,refresh}:{data:Dashboard;query:string;refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(""); const q=query.toLowerCase();const rows=data.inventory.filter(p=>!q||`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(q));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const payload={name:f.get("name"),sku:f.get("sku"),category:f.get("category"),priceCents:Math.round(Number(f.get("price"))*100),stock:Number(f.get("stock")),reorderPoint:Number(f.get("reorderPoint"))};const r=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json() as {error?:string};setMessage(r.ok?"Produto cadastrado.":b.error??"Erro ao salvar.");if(r.ok){setOpen(false);await refresh()}}
 return <><Panel title="Catálogo de produtos" subtitle={`${rows.length} produtos encontrados`} action={<button className="primary-commerce-action" onClick={()=>setOpen(true)}><Plus size={14}/>Novo produto</button>}><div className="catalog-grid">{rows.map(p=>{const available=p.stock-p.reservedStock;return <article key={p.id}><span className="product-symbol"><Box/></span><small>{p.sku} · {p.category}</small><h3>{p.name}</h3><strong>{currency(p.priceCents)}</strong><footer><span className={available<=p.reorderPoint?"critical-badge":"healthy-badge"}>{available} disponíveis</span><small>Mín. {p.reorderPoint}</small></footer></article>})}</div></Panel>{open&&<Modal title="Novo produto" close={()=>setOpen(false)}><form onSubmit={save}><label>Nome<input name="name" required minLength={2}/></label><label>SKU<input name="sku" required pattern="[A-Za-z0-9-]{3,24}"/></label><label>Categoria<input name="category" required/></label><label>Preço<input name="price" type="number" step=".01" min=".01" required/></label><label>Estoque inicial<input name="stock" type="number" min="0" required/></label><label>Ponto de reposição<input name="reorderPoint" type="number" min="0" required/></label><button className="primary-commerce-action"><Save size={14}/>Salvar produto</button></form></Modal>}<Toast message={message} close={()=>setMessage("")}/></>
}

export function CustomersWorkspace({data,query,refresh}:{data:Dashboard;query:string;refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState("");const q=query.toLowerCase();const rows=data.customers.filter(c=>!q||`${c.name} ${c.email}`.toLowerCase().includes(q));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/customers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const b=await r.json() as {error?:string};setMessage(r.ok?"Cliente cadastrado.":b.error??"Erro ao salvar.");if(r.ok){setOpen(false);await refresh()}}
 return <><Panel title="Base de clientes" subtitle="Segmentação, recorrência e receita" action={<button className="primary-commerce-action" onClick={()=>setOpen(true)}><Plus size={14}/>Novo cliente</button>}><div className="customer-grid">{rows.map(c=><article key={c.id}><i>{initials(c.name)}</i><div><h3>{c.name}</h3><p>{c.email}</p><span>{segmentCopy[c.segment]}</span></div><b>{currency(c.totalSpentCents)}<small>{c.orderCount} pedidos</small></b></article>)}</div></Panel>{open&&<Modal title="Novo cliente" close={()=>setOpen(false)}><form onSubmit={save}><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Segmento<select name="segment"><option value="new">Novo</option><option value="returning">Recorrente</option><option value="vip">VIP</option></select></label><button className="primary-commerce-action"><Save size={14}/>Salvar cliente</button></form></Modal>}<Toast message={message} close={()=>setMessage("")}/></>
}

export function InventoryWorkspace({data,query,refresh}:{data:Dashboard;query:string;refresh:()=>Promise<void>}){
 const [chosen,setChosen]=useState<Product|null>(null),[message,setMessage]=useState("");const q=query.toLowerCase();const rows=data.inventory.filter(p=>p.status==="active"&&(!q||`${p.name} ${p.sku}`.toLowerCase().includes(q)));
 async function restock(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!chosen)return;const f=new FormData(e.currentTarget);const r=await fetch("/api/inventory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:chosen.id,quantity:Number(f.get("quantity"))})});const b=await r.json() as {error?:string;message?:string};setMessage(r.ok?b.message??"Reposição registrada.":b.error??"Erro na reposição.");if(r.ok){setChosen(null);await refresh()}}
 return <><Panel title="Controle de estoque" subtitle="Disponibilidade calculada com reservas ativas"><div className="inventory-list">{rows.map(p=>{const available=p.stock-p.reservedStock;return <article key={p.id}><span><Box/></span><div><h3>{p.name}</h3><p>{p.sku} · mínimo {p.reorderPoint}</p></div><b className={available<=p.reorderPoint?"danger":""}>{available}<small> disponíveis</small></b><button onClick={()=>setChosen(p)}><RotateCcw size={14}/>Repor</button></article>})}</div></Panel>{chosen&&<Modal title={`Repor ${chosen.name}`} close={()=>setChosen(null)}><form onSubmit={restock}><label>Quantidade<input name="quantity" type="number" min="1" max="10000" required autoFocus/></label><button className="primary-commerce-action"><Save size={14}/>Registrar entrada</button></form></Modal>}<Toast message={message} close={()=>setMessage("")}/></>
}

export function ReportsWorkspace(){const [period,setPeriod]=useState(30),[data,setData]=useState<Report|null>(null);useEffect(()=>{fetch(`/api/reports?period=${period}`).then(r=>r.ok?r.json():null).then(setData)},[period]);return <Panel title="Relatório comercial" subtitle="Indicadores calculados diretamente da operação" action={<select value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select>}>{data?<><section className="workspace-kpis"><article><BarChart3/><span><small>Receita</small><strong>{currency(data.summary.revenueCents)}</strong></span></article><article><ShoppingCart/><span><small>Pedidos</small><strong>{data.summary.orderCount}</strong></span></article><article><CheckCircle2/><span><small>Envio concluído</small><strong>{data.summary.fulfillmentRate}%</strong></span></article></section><div className="report-bars">{data.channels.map(c=><div key={c.channel}><span>{channelCopy[c.channel]}</span><i><b style={{width:`${Math.min(100,c.revenueCents/Math.max(data.summary.revenueCents,1)*100)}%`}}/></i><strong>{currency(c.revenueCents)}</strong></div>)}</div></>:<div className="loading-state">Calculando relatório...</div>}</Panel>}

export function SettingsWorkspace({session}:{session:Session|null}){return <div className="settings-grid"><Panel title="Acesso atual" subtitle="Permissões aplicadas nesta sessão"><div className="access-card"><i>{initials(session?.name??"Lucas Soares")}</i><div><h3>{session?.name??"Lucas Soares"}</h3><p>{session?.email??"Carregando identificação..."}</p><span>{session?roleCopy[session.role]:"Verificando"}</span></div></div></Panel><Panel title="Controles da operação" subtitle="Regras que protegem alterações sensíveis"><ul className="control-list"><li><CheckCircle2/>Mudanças de pedido seguem transições válidas</li><li><CheckCircle2/>Estoque registra cada entrada e saída</li><li><CheckCircle2/>Ações de escrita exigem permissão</li></ul></Panel></div>}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <><button className="commerce-modal-backdrop" onClick={close} aria-label="Fechar"/><div className="order-modal compact-modal"><header><div><small>TREVIL · OPERAÇÃO</small><h2>{title}</h2></div><button onClick={close} aria-label="Fechar"><X/></button></header>{children}</div></>}
