import { getDatabase } from "./runtime";

let initialization: Promise<void> | null = null;

export function ensureCommerceData() {
  initialization ??= initialize();
  return initialization;
}

async function initialize() {
  const db = await getDatabase();
  await db.batch([
    db.prepare(`CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY, sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
      category TEXT NOT NULL, price_cents INTEGER NOT NULL, stock INTEGER NOT NULL DEFAULT 0,
      reserved_stock INTEGER NOT NULL DEFAULT 0, reorder_point INTEGER NOT NULL DEFAULT 5,
      status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT products_stock_bounds_check CHECK (stock >= 0 AND reserved_stock >= 0 AND reserved_stock <= stock))`),
    db.prepare("CREATE INDEX IF NOT EXISTS products_stock_idx ON products(stock)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS customers (
      id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
      segment TEXT NOT NULL DEFAULT 'new', total_spent_cents INTEGER NOT NULL DEFAULT 0,
      order_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
    db.prepare(`CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, number TEXT NOT NULL UNIQUE, customer_id INTEGER NOT NULL,
      status TEXT NOT NULL, payment_status TEXT NOT NULL, total_cents INTEGER NOT NULL,
      channel TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id))`),
    db.prepare("CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status)"),
    db.prepare("CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at)"),
    db.prepare("CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders(customer_id)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS order_items (
      id SERIAL PRIMARY KEY, order_id INTEGER NOT NULL, product_id INTEGER NOT NULL,
      quantity INTEGER NOT NULL, unit_price_cents INTEGER NOT NULL,
      FOREIGN KEY (order_id) REFERENCES orders(id), FOREIGN KEY (product_id) REFERENCES products(id))`),
    db.prepare("CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items(order_id)"),
    db.prepare("CREATE INDEX IF NOT EXISTS order_items_product_idx ON order_items(product_id)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS order_events (
      id SERIAL PRIMARY KEY, order_id INTEGER NOT NULL, action TEXT NOT NULL,
      from_status TEXT, to_status TEXT NOT NULL, actor TEXT NOT NULL, details TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id))`),
    db.prepare("CREATE INDEX IF NOT EXISTS order_events_order_idx ON order_events(order_id)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS stock_movements (
      id SERIAL PRIMARY KEY, product_id INTEGER NOT NULL, order_id INTEGER,
      type TEXT NOT NULL, quantity INTEGER NOT NULL, actor TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (product_id) REFERENCES products(id), FOREIGN KEY (order_id) REFERENCES orders(id))`),
    db.prepare("CREATE INDEX IF NOT EXISTS stock_movements_product_idx ON stock_movements(product_id)"),
    db.prepare("CREATE INDEX IF NOT EXISTS stock_movements_order_idx ON stock_movements(order_id)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS user_roles (
      email TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'viewer',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  ]);

  const existing = await db.prepare("SELECT COUNT(*) AS count FROM products").first<{ count: number }>();
  if (Number(existing?.count ?? 0) > 0) return;

  await db.batch([
    db.prepare("INSERT INTO products (sku,name,category,price_cents,stock,reserved_stock,reorder_point) VALUES (?,?,?,?,?,?,?)").bind("CAM-ESS-001", "Camiseta Essential", "Vestuário", 8990, 8, 3, 10),
    db.prepare("INSERT INTO products (sku,name,category,price_cents,stock,reserved_stock,reorder_point) VALUES (?,?,?,?,?,?,?)").bind("MOC-URB-002", "Moletom Urban", "Vestuário", 18990, 24, 5, 8),
    db.prepare("INSERT INTO products (sku,name,category,price_cents,stock,reserved_stock,reorder_point) VALUES (?,?,?,?,?,?,?)").bind("BON-CLB-003", "Boné Club", "Acessórios", 6990, 4, 2, 8),
    db.prepare("INSERT INTO products (sku,name,category,price_cents,stock,reserved_stock,reorder_point) VALUES (?,?,?,?,?,?,?)").bind("BAG-DAY-004", "Bag Everyday", "Acessórios", 12990, 17, 4, 6),
    db.prepare("INSERT INTO products (sku,name,category,price_cents,stock,reserved_stock,reorder_point) VALUES (?,?,?,?,?,?,?)").bind("CAL-RIB-005", "Calça Rib", "Vestuário", 15990, 31, 6, 10),
    db.prepare("INSERT INTO customers (name,email,segment,total_spent_cents,order_count) VALUES (?,?,?,?,?)").bind("Ana Martins", "ana@example.com", "vip", 78360, 8),
    db.prepare("INSERT INTO customers (name,email,segment,total_spent_cents,order_count) VALUES (?,?,?,?,?)").bind("Rafael Lima", "rafael@example.com", "returning", 34870, 4),
    db.prepare("INSERT INTO customers (name,email,segment,total_spent_cents,order_count) VALUES (?,?,?,?,?)").bind("Beatriz Costa", "bia@example.com", "new", 12990, 1),
    db.prepare("INSERT INTO customers (name,email,segment,total_spent_cents,order_count) VALUES (?,?,?,?,?)").bind("Diego Souza", "diego@example.com", "returning", 45970, 3),
    db.prepare("INSERT INTO customers (name,email,segment,total_spent_cents,order_count) VALUES (?,?,?,?,?)").bind("Camila Rocha", "camila@example.com", "new", 8990, 1),
  ]);

  await db.batch([
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '2 hours')").bind("#COS-1048", 1, "processing", "paid", 27980, "store"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '5 hours')").bind("#COS-1047", 3, "paid", "paid", 12990, "social"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '1 day')").bind("#COS-1046", 2, "shipped", "paid", 24980, "marketplace"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '2 days')").bind("#COS-1045", 4, "delivered", "paid", 34980, "store"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '3 days')").bind("#COS-1044", 1, "delivered", "paid", 18990, "store"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '4 days')").bind("#COS-1043", 5, "delivered", "paid", 8990, "social"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '5 days')").bind("#COS-1042", 2, "delivered", "paid", 31880, "marketplace"),
    db.prepare("INSERT INTO orders (number,customer_id,status,payment_status,total_cents,channel,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP - INTERVAL '6 days')").bind("#COS-1041", 4, "canceled", "refunded", 6990, "store"),
  ]);

  await db.batch([
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(1, 1, 1, 8990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(1, 2, 1, 18990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(2, 4, 1, 12990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(3, 1, 2, 8990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(3, 3, 1, 6990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(4, 2, 1, 18990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(4, 5, 1, 15990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(5, 2, 1, 18990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(6, 1, 1, 8990),
    db.prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price_cents) VALUES (?,?,?,?)").bind(7, 5, 2, 15940),
  ]);

  await db.batch([
    db.prepare("UPDATE products SET reserved_stock = CASE id WHEN 1 THEN 3 WHEN 2 THEN 5 WHEN 3 THEN 2 WHEN 4 THEN 4 WHEN 5 THEN 6 ELSE reserved_stock END"),
    db.prepare("INSERT INTO order_events (order_id,action,from_status,to_status,actor,details) VALUES (1,'created',NULL,'processing','Sistema','Pedido importado da loja própria')"),
    db.prepare("INSERT INTO order_events (order_id,action,from_status,to_status,actor,details) VALUES (2,'created',NULL,'paid','Sistema','Pagamento aprovado pelo social commerce')"),
    db.prepare("INSERT INTO order_events (order_id,action,from_status,to_status,actor,details) VALUES (3,'shipped','processing','shipped','Marina Costa','Pedido entregue à transportadora')"),
  ]);
}
